development:
  secret_key_base: key
  stripe_secret_key: 'sk_test_51M6rQqSEPNqv3a1zy89NXWTEsgfhDcbbZlcjeer5Fh2BJuugMWTtmjR2nMcJjo0rph93z7TfJvhYx6VZAtfDDh4G0008BlvejH'
  stripe_publishable_key: "pk_test_51M6rQqSEPNqv3a1zSNrYK26cFigAuA9EEyBYZTRzDk0R9YUJQp3HghnwBmNLX5Nc3vgh2vnhJ4Ubx4X2LRd91T4n00Gd5egmiV"